### ISSUE TITLE
Add GitHub actions to test install scripts

### ISSUE THREAD

**Issue by cjfullerton** [hpcflow/install-scripts#39]
There is no testing for install scripts. We should add some, for Powershell in particular.
```[tasklist]
### Tasks
- [x] GHA for Linux integration test
- [x] GHA for MacOS integration test
- [x] GHA for Powershell integration test
- [x] Windows script gets name of artifact from script output
- [ ] https://github.com/hpcflow/install-scripts/issues/44
```

**Comment by cjfullerton** [comment]
Now runs test suite on installed artifact. Needed to run directly as couldn't use `source .bashrc` to get symlinks. Need a way to get filename of installed artifact.

**Comment by cjfullerton** [comment]
Workflows work on Linux, macOS, Windows/powershell.

Windows workflow needs to be able to get name of installed artifact - save script output and pull it from this.

Check if script can be run on modern and classic versions of powershell on a GHA runner.
